### ISSUE TITLE
Online version seems to not be working (with zotero v6)

### ISSUE THREAD

**Issue by EricThomson** [mattaq31/Zotero-Report-Cleaner#1]
I found the online version: https://matthewaquilina.net/zotero_report_cleaner

I'm creating my reports with zotero 6 and not getting expected outputs (I seem to be getting same report out).  I wonder if you have any interest in getting it working on v6. I could probably help with that if you are interested.

**Comment by mattaq31** [comment]
Hi @EricThomson thanks for checking in on this app and your offer to help.  It's been a while since I created this repo, and it was mostly meant as a small project for me to train on website hosting and cloud functions deployment.

I've checked the issue you've mentioned and indeed it seems like report generation in Zotero 6 has changed slightly and the old program no longer works.  However, it only needed a quick fix - the code now looks for table tags if it can't find any tbody tags.  I've deployed the update both here and to the online version - everything should now work correctly.

Out of curiosity, what is your use-case for this app?

**Comment by EricThomson** [comment]
Thanks for the reply it's a great idea for an application!

I'm summarizing/collating systems neuroscience literature for the last decade after focusing more on software stuff for a couple of years. I want more fine-grained control over the reports because they are getting pretty long 😄 Note I haven't event tested the cli / local versions yet that's ultimately what I'd like to play around with. I'm new to zotero and it seems great (e.g., pyzotero will let me do ML on my lit to see trends). 

I installed the [report customizer extension](https://github.com/retorquere/zotero-report-customizer) but it is only working up to v5. There are two open issues about this [[1](https://github.com/retorquere/zotero-report-customizer/issues/79)][[2](https://github.com/retorquere/zotero-report-customizer/issues/88)], but since yours is in Python I am more likely to be able to figure it out and actually tinker with it. 

Note I just tested it again and they still seem to look the same:    
- [Original report](https://drive.google.com/file/d/1s-t5XEjXXgTvmiHSwO7VsVabC4zYU78a/view?usp=sharing)
- [Edited report](https://drive.google.com/file/d/1qlO8fp_UiqQWl05zrJT22RfHAtIIObY8/view?usp=sharing)

**Comment by mattaq31** [comment]
Hi @EricThomson I see - the reports you sent have a different format to mine.  Are you using Windows by any chance?  I'm generating my reports on Mac.

In any case I was able to edit things again to accept your report format too - can you check on the website again?  Make sure to clear any of the website's cookies first to ensure it's on the latest version.

**Comment by EricThomson** [comment]
Yes I’m on Windows 😭 

Thanks for reply I’m currently driving up coast but will test when I  hit destination and let you know!

Edit: I just tried it and it seems to be working! Will close issue thanks a lot for the help!
